language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install libroadrunner # (not supported in py 3.9 yet)
  - pip install pytest-cov pytest
  - pip install codecov
  - pip install .

# command to run tests
script:
  - pytest --cov-report term --cov=peppercornenumerator/

after_success:
  - codecov
