language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

# command to install dependencies
install:
  - pip install libroadrunner # somehow the imports fail atm
  - pip install .[dev]

# command to run tests
script:
  - pytest --cov-report term --cov=peppercornenumerator/

after_success:
  - codecov
