SLC_output.pil : 
	python ../../../enumerator.py --infile SLC_standard_input.enum -i standard --outfile SLC_output.pil -o pil
	
SLC_output-condensed.pil : 
	python ../../../enumerator.py -c --infile SLC_standard_input.enum -i standard --outfile SLC_output-condensed.pil -o pil